name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thank you for raising an issue! Please make sure you have given us enough context and we will review it as soon as possible. ⏲️ If you don't hear back from anyone within the next week, feel free to reach out to one of the maintainers. 💛"
          pr-message: "Thanks for opening this pull request! Please make sure you have followed our contributing guidelines and we will review it as soon as possible. ⏲️ If you don't hear back from anyone within the next week, feel free to reach out to one of the maintainers. 💛"
